### PR TITLE
Fix #77: Unify `v1*_only` parameter into `target_version`

### LINKED ISSUE #77: Unifying target version parameter for `upgrade_document`
The current implementation of `upgrade_document` has the following signature:
```python
def upgrade_document(
    document: Any, v1_only: bool, v1_1_only: bool, output_dir: str, imports: Set[str]
) -> Any:
```
IMO it is not scalable for future releases because the new parameter should be added for each release version.

How about fixing the signature as follows?
```python
def upgrade_document(
    document: Any, target_version: Optional[str] = "latest", output_dir: str, imports: Set[str]
) -> Any:
```
The `target_version` parameter takes a version string such as `"v1.0"`, `"v1.1"`, `"v1.2"` and `"latest"` (same as `"v1.2"`).
It enables upgrading `upgrade_document` to other future release versions without changing its signature.

If it is OK for this change, I will send a pull request for it.

### PR DESCRIPTION
**Pull request by tom-tan**
It introduces `target_version` parameter to replace `v1*_only` parameters.
It also make `imports` parameter as a default parameter to make `target_version` optional.

Note:
- Current implementation prints an error message and returns nothing if a given CWL doc has unsupported `cwlVersion`. Can we leave it as is or fix it to raise an exception, for example?

### CODE REVIEW

**Comment by mr-c** [comment]
The `imports` set needs to be external of the function, as it is used to prevent duplicate upgrading of the same external file, when upgrading more than one primary document.

**Comment by tom-tan** [comment]
Thank you for your advice.
Now `run` calls `upgrade_document` with a set.
It prevents duplicate upgrading while keeping the API of `upgrade_document` simple.

**Comment by mr-c** [comment]
> Thank you for your advice. Now `run` calls `upgrade_document` with a set. It prevents duplicate upgrading while keeping the API of `upgrade_document` simple.

Thanks!

I'm seeing some code coverage issues; 24% is rather low. You can run `make diff-cover` locally to get a line-by-line report, or wait for the CI to finish and check https://github.com/common-workflow-language/cwl-upgrader/pull/79/files for annotations about lack of test coverage.

**Comment by tom-tan** [comment]
Added!

Note that the current implementation of `upgrade_document` only dumps the upgrade documents for `steps` fields and does not dump the document for a given CWL that is passed to the parameter (it is done by `cwlupgrader.main.run`).
Fixing this issue is out of scope of this request (will be fixed when #78 is solved).

**Comment by tom-tan** [comment]
Thanks!

**Pull request merged**
